################################################################################
# LIB:         claude-setup.sh
# DESCRIPTION: Claude Code configuration generation for Shikomi
#
# FUNCTIONS:   generate_claude_md(), init_session_diary()
#
# GLOBALS READ:
#   SCRIPT_NAME, SCRIPT_TEMPLATE, SCRIPT_VERSION, IS_MONOREPO,
#   SECRETS_USED, ONEPASSWORD_SECRETS[], PROJECT_DIR
#
# GLOBALS WRITTEN: None (writes to $PROJECT_DIR/CLAUDE.md,
#                        $PROJECT_DIR/SESSION_DIARY.md)
################################################################################

function generate_claude_md() {
    local claude_path="$PROJECT_DIR/CLAUDE.md"
    local script_type
    if [[ "$SCRIPT_TEMPLATE" == "ea" ]]; then
        script_type="Jamf Pro Extension Attribute"
    else
        script_type="macOS Management Script (Jamf Pro)"
    fi

    # Determine secret management context
    local secret_section="None configured"
    if [[ "$SECRETS_USED" == true ]]; then
        if [[ ${#ONEPASSWORD_SECRETS[@]} -gt 0 ]]; then
            secret_section="1Password CLI (\`op read\`) - secrets are fetched at runtime"
        else
            secret_section="Local secrets file (\`~/.jamf_secrets\`) - sourced at runtime"
        fi
    fi

    # --- Write CLAUDE.md ---
    cat > "$claude_path" << CLAUDEEOF
# CLAUDE.md

This file provides guidance to Claude Code when working in this repository.

## Project Overview

- **Project:** ${SCRIPT_NAME}
- **Type:** ${script_type}
- **Generated by:** Shikomi v${SCRIPT_VERSION}
- **Created:** $(date +%Y-%m-%d)

## Shell Script Conventions

- **Compatibility:** bash 3.2+ (macOS default). No associative arrays, no \${var,,} syntax.
- **Linting:** All scripts must pass \`shellcheck --severity=warning\`
- **Shebang:** \`#!/bin/bash\`
- **Logging:** Use the \`log\`, \`log_warn\`, \`log_error\`, \`log_success\` functions defined in the script
- **Exit codes:** Exit 0 on success, non-zero on failure

## Versioning

- Version is stored in the script header as \`readonly SCRIPT_VERSION="x.y.z"\`
- **Always** use \`bump-version\` to change versions — never edit version strings manually
- \`bump-version\` updates the script, README, and CHANGELOG simultaneously
- \`bump-version\` is installed system-wide via Shikomi's \`install.sh\`
- Follow semantic versioning: major.minor.patch

## Secret Management

- **Method:** ${secret_section}
- **NEVER** commit \`.jamf_secrets\`, API keys, \`.p8\` files, or credentials
- **NEVER** hardcode secrets in scripts — use parameter injection or 1Password
- The \`.gitignore\` blocks common secret file patterns
CLAUDEEOF

    # Add 1Password references if any
    if [[ ${#ONEPASSWORD_SECRETS[@]} -gt 0 ]]; then
        {
            echo ""
            echo "### 1Password References"
            echo ""
            printf -- '- `%s`\n' "${ONEPASSWORD_SECRETS[@]}"
        } >> "$claude_path"
    fi

    # Add security rules
    cat >> "$claude_path" << 'CLAUDEEOF'

## Security Rules

- Pre-commit hooks scan for secrets before every commit
- Never commit: `.env`, `.jamf_secrets`, `secrets.sh`, `*.p8`, `*auth*.json`
- Test scripts locally before deploying to Jamf Pro
CLAUDEEOF

    # Add EA-specific guidelines if applicable
    if [[ "$SCRIPT_TEMPLATE" == "ea" ]]; then
        cat >> "$claude_path" << CLAUDEEOF

## Extension Attribute Guidelines

- Output MUST be in \`<result>VALUE</result>\` format
- Script should be silent except for the result line
- Handle errors gracefully — output \`Error\` or \`Not Available\` rather than failing
- Test locally: \`./${SCRIPT_NAME}.sh\` should print a single \`<result>...</result>\` line
CLAUDEEOF
    fi

    # Add session diary instruction
    cat >> "$claude_path" << 'CLAUDEEOF'

## Session Diary

After completing any meaningful unit of work (investigation, code change, config change,
decision, or troubleshooting), append a timestamped entry to `./SESSION_DIARY.md`.

Format each entry as:

### YYYY-MM-DD HH:MM — [Brief Title]

**Investigated:** What was explored or diagnosed
**Changed:** Files modified, commands run, config altered (with paths)
**Decided:** What direction was chosen
**Why:** Rationale, trade-offs considered, constraints that drove the decision
CLAUDEEOF
}

function init_session_diary() {
    local diary_path="$PROJECT_DIR/SESSION_DIARY.md"
    local script_type
    if [[ "$SCRIPT_TEMPLATE" == "ea" ]]; then
        script_type="Extension Attribute"
    else
        script_type="Regular Script"
    fi

    local mode
    if [[ "$IS_MONOREPO" == true ]]; then
        mode="Monorepo"
    else
        mode="New Project (micro-repo)"
    fi

    cat > "$diary_path" << DIARYEOF
# Session Diary

---

### $(date '+%Y-%m-%d %H:%M') — Project scaffolded by Shikomi

**Investigated:** N/A (initial generation)
**Changed:** Project created with Shikomi v${SCRIPT_VERSION}
  - Generated: ${SCRIPT_NAME}.sh (${script_type}, v1.0.0)
  - Template: ${script_type}
  - Mode: ${mode}
**Decided:** Initial project structure
**Why:** Generated by Shikomi automated scaffolding

---
DIARYEOF
}
